name: test GitHub Action
on:
  workflow_dispatch:


jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsutils@main
      - uses: wechuli/actionsutils@main
        with:
          tasks: 'context,oidctoken'
